USE RESTAURANTES;

SELECT * FROM CLIENTE;



SELECT * FROM MARMITA WHERE preco = 15.00;

SELECT * FROM MARMITA WHERE preco <> 20.00;

SELECT * FROM PEDIDO WHERE data_pedido > '2025-09-01';

SELECT * FROM CLIENTE WHERE data_nascimento < '2000-01-01';

SELECT * FROM MARMITA WHERE preco >= 25.00;

SELECT * FROM MARMITA WHERE preco <= 10.00;

SELECT * FROM CLIENTE WHERE endereco = 'Centro';

SELECT * FROM ENTREGADOR WHERE empresa_id = 1;



SELECT * FROM MARMITA WHERE tamanho IN ('Pequena', 'Média', 'Grande');

SELECT * FROM ENTREGADOR WHERE empresa_id NOT IN (2, 3, 5);



SELECT * FROM ENTREGADOR WHERE celular IS NULL;

SELECT * FROM CLIENTE WHERE endereco IS NOT NULL;

SELECT * FROM PEDIDO WHERE taxa_entrega IS NULL;





SELECT * FROM MARMITA WHERE preco BETWEEN 10.00 AND 25.00;

SELECT * FROM PEDIDO WHERE data_pedido BETWEEN '2025-09-01' AND '2025-09-05';

SELECT * FROM CLIENTE WHERE nome LIKE 'A%';

SELECT * FROM ENTREGADOR WHERE cpf LIKE '%99';

SELECT * FROM MARMITA WHERE descricao LIKE '%Frango%';

SELECT * FROM MARMITA WHERE preco > 20.00 AND tamanho = 'Grande';

SELECT * FROM PEDIDO WHERE status = 'Entregue' OR status = 'Em andamento';




SELECT MAX(preco) FROM MARMITA;

SELECT MIN(preco) FROM MARMITA;

SELECT AVG(preco) FROM MARMITA;

SELECT COUNT(*) FROM CLIENTE;

SELECT COUNT(*) FROM PEDIDO;

SELECT SUM(preco) FROM MARMITA;
